- README.md
> [IDVA5-375]- eric setup

- src/main/java/uk/gov/companieshouse/acsp/controllers/TransactionController.java
- src/main/java/uk/gov/companieshouse/acsp/service/TransactionService.java
- src/main/java/uk/gov/companieshouse/acsp/util/Constants.java
- src/test/java/uk/gov/companieshouse/acsp/controllers/CostControllerTest.java
- src/test/java/uk/gov/companieshouse/acsp/controllers/TransactionControllerTest.java
- src/test/java/uk/gov/companieshouse/acsp/service/CostServiceTest.java
- src/test/java/uk/gov/companieshouse/acsp/service/TransactionServiceTest.java
Transaction service integration with get update and close endpoint
> Transaction service integration

- src/main/resources/application.yaml
Adding context path to the service
> Adding context path to the service

- pom.xml
Adding dependencies related to security api, jib and sonar.
* [ x] New feature
> Adding pom dependencies

- pom.xml
- suppress.xml
> Fixing multiple CVEs

- pom.xml
> Removing duplicate

- routes.yaml
> adding routes.yml file

- terraform/groups/ecs-service/main.tf
> terraform module version update for eric

- pom.xml
> springframework upgrade fix

- terraform/groups/ecs-service/vault.tf
> vault config changes

- terraform/groups/ecs-service/locals.tf
- terraform/groups/ecs-service/main.tf
> lb listner rule priority change

- terraform/groups/ecs-service/locals.tf
> healthcheck_path update

- terraform/groups/ecs-service/locals.tf
> fixing typo

- ecs-image-build/docker_start.sh
- terraform/groups/ecs-service/locals.tf
> fixing port for healthchecks

- ecs-image-build/docker_start.sh
- terraform/groups/ecs-service/locals.tf
> reverting port number

- src/main/resources/application.yaml
> Changing healthCheck url

- src/main/java/uk/gov/companieshouse/acsp/controllers/OfficerController.java
- src/main/java/uk/gov/companieshouse/acsp/controllers/TransactionController.java
- src/main/java/uk/gov/companieshouse/acsp/service/OfficerService.java
- src/main/java/uk/gov/companieshouse/acsp/service/TransactionService.java
- src/main/java/uk/gov/companieshouse/acsp/util/Constants.java
- src/test/java/uk/gov/companieshouse/acsp/controllers/OfficerControllerTest.java
- src/test/java/uk/gov/companieshouse/acsp/service/OfficerServiceTest.java
add endpoint to fetch directors related information
> add endpoint to fetch directors related information

- Makefile
- pom.xml
Changing the way Sonar runs
Adding Sonar properties in pom.xml and also making some changes in Makefile.
> Changing the way Sonar runs

- pom.xml
> change to fix incorrect sonar url in slack alerts

- src/main/java/uk/gov/companieshouse/acsp/Exception/ServiceException.java
- src/main/java/uk/gov/companieshouse/acsp/controllers/CompanyProfileController.java
- src/main/java/uk/gov/companieshouse/acsp/service/CompanyProfileService.java
- src/test/java/uk/gov/companieshouse/acsp/controllers/CompanyProfileControllerTest.java
- src/test/java/uk/gov/companieshouse/acsp/service/CompanyProfileServiceTest.java
> companyID not found error handling

- src/main/java/uk/gov/companieshouse/acsp/controllers/AcspController.java
> Return proper response for data not found

- terraform/groups/ecs-service/data.tf
- terraform/groups/ecs-service/locals.tf
- terraform/groups/ecs-service/main.tf
> changes to lb and tf ver

- terraform/groups/ecs-service/main.tf
> reverting the TF ver for now

- terraform/groups/ecs-service/main.tf
> testing Joel bug fix branch

- terraform/groups/ecs-service/main.tf
> correcting typo

- terraform/groups/ecs-service/main.tf
> reverting test branch ref

- terraform/groups/ecs-service/profiles/staging-eu-west-2/staging/vars
> adding staging configs

- suppress.xml
_The CVE is still under analysis hence no fix for it is available
> The CVE is still under analysis hence no fix for it is available

- pom.xml
- suppress.xml
> The CVE fix

- pom.xml
> Fixing CVE cve-2024-22262

- terraform/groups/ecs-service/data.tf
- terraform/groups/ecs-service/main.tf
> move to api lb

- terraform/groups/ecs-service/main.tf
> updating terraform mod ver

- terraform/groups/ecs-service/main.tf
> move to lower TF version

- terraform/groups/ecs-service/main.tf
> one version up

- terraform/groups/ecs-service/main.tf
> reverting to previous working ver

- terraform/groups/ecs-service/profiles/development-eu-west-2/cidev/vars
- terraform/groups/ecs-service/profiles/development-eu-west-2/phoenix1/vars
- terraform/groups/ecs-service/variables.tf
> changing default env file toggle to true

- terraform/groups/ecs-service/data.tf
- terraform/groups/ecs-service/main.tf
- terraform/groups/ecs-service/variables.tf
Added multilb changes to main.tf, data.tf and variables.tf
> added multilb changes to main.tf, data.tf and variables.tf

- terraform/groups/ecs-service/variables.tf
> cloudwatch var changes

- src/main/java/uk/gov/companieshouse/acsp/controllers/AcspController.java
- src/main/java/uk/gov/companieshouse/acsp/repositories/AcspRepository.java
- src/main/java/uk/gov/companieshouse/acsp/service/AcspService.java
- src/test/java/uk/gov/companieshouse/acsp/controllers/AcspControllerTest.java
- src/test/java/uk/gov/companieshouse/acsp/service/AcspServiceTest.java
Added endpoint to check for applications for current logged-in user, returns 204 if an application has been found else will return 404
IDVA5-800
> Added endpoint to check for applications for current logged-in user.

- src/main/java/uk/gov/companieshouse/acsp/models/enums/RoleType.java
Updated RoleType enum to include all role types
IDVA5-783
> Updated RoleType enum to include all role types

- src/main/java/uk/gov/companieshouse/acsp/controllers/AcspController.java
- src/main/java/uk/gov/companieshouse/acsp/controllers/FilingsController.java
- src/main/java/uk/gov/companieshouse/acsp/models/filing/ACSP.java
- src/main/java/uk/gov/companieshouse/acsp/models/filing/Address.java
- src/main/java/uk/gov/companieshouse/acsp/models/filing/Filing.java
- src/main/java/uk/gov/companieshouse/acsp/models/filing/Item.java
- src/main/java/uk/gov/companieshouse/acsp/models/filing/Presenter.java
- src/main/java/uk/gov/companieshouse/acsp/models/filing/Submission.java
- src/main/java/uk/gov/companieshouse/acsp/service/AcspService.java
- src/main/java/uk/gov/companieshouse/acsp/service/FilingsService.java
- src/main/java/uk/gov/companieshouse/acsp/util/Constants.java
- src/main/resources/application.properties
- src/test/java/uk/gov/companieshouse/acsp/controllers/AcspControllerTest.java
- src/test/java/uk/gov/companieshouse/acsp/controllers/FilingsControllerTest.java
- src/test/java/uk/gov/companieshouse/acsp/service/AcspServiceTest.java
- src/test/java/uk/gov/companieshouse/acsp/service/FilingServiceTest.java
- src/test/resources/application.properties
> Adding filings endpoint

- terraform/groups/ecs-service/main.tf
> TF ver update to latest

- terraform/groups/ecs-service/main.tf
> changing to last know working ver

- terraform/groups/ecs-service/main.tf
> revert TF module ver

- routes.yaml
> changes to routes.yaml

- src/main/java/uk/gov/companieshouse/acsp/controllers/AcspController.java
- src/main/java/uk/gov/companieshouse/acsp/controllers/FilingsController.java
- src/main/java/uk/gov/companieshouse/acsp/exception/SubmissionNotLinkedToTransactionException.java
- src/main/java/uk/gov/companieshouse/acsp/service/AcspService.java
- src/main/java/uk/gov/companieshouse/acsp/service/FilingsService.java
- src/main/java/uk/gov/companieshouse/acsp/util/Constants.java
- src/main/java/uk/gov/companieshouse/acsp/util/TransactionUtils.java
- src/test/java/uk/gov/companieshouse/acsp/controllers/AcspControllerTest.java
- src/test/java/uk/gov/companieshouse/acsp/controllers/FilingsControllerTest.java
- src/test/java/uk/gov/companieshouse/acsp/service/AcspServiceTest.java
- src/test/java/uk/gov/companieshouse/acsp/service/FilingServiceTest.java
- src/test/java/uk/gov/companieshouse/acsp/util/TransactionUtilsTest.java
Added functionality for verify linked transaction
https://companieshouse.atlassian.net/browse/IDVA5-787
* [x ] New feature
* [ x] I have added unit tests for new code that I have added
* [ x] I have added/updated functional tests where appropriate
* [ x] The code follows our [coding standards](https://github.com/companieshouse/styleguides/blob/master/java.md)
> verify linked transaction for get request

- routes.yaml
Adding private urls in routes.yaml for eric
> Adding private urls in routes.yaml for eric

- src/main/java/uk/gov/companieshouse/acsp/controllers/FilingsController.java
- src/test/java/uk/gov/companieshouse/acsp/controllers/FilingsControllerTest.java
> Removing eric header

- src/main/java/uk/gov/companieshouse/acsp/controllers/FilingsController.java
> removing private from url

- terraform/groups/ecs-service/locals.tf
> Adding  urls in locals.tf for eric

- src/main/java/uk/gov/companieshouse/acsp/controllers/FilingsController.java
- src/main/java/uk/gov/companieshouse/acsp/models/filing/ACSP.java
- src/main/java/uk/gov/companieshouse/acsp/models/filing/Address.java
- src/main/java/uk/gov/companieshouse/acsp/service/FilingsService.java
- src/test/java/uk/gov/companieshouse/acsp/service/FilingServiceTest.java
Adding companyDetails in the json
IDVA5-772
* [ x] Bug fix
> Adding companyDetails in the json

- src/main/java/uk/gov/companieshouse/acsp/controllers/FilingsController.java
Removing private from endpoint
> Removing private from endpoint

- src/main/java/uk/gov/companieshouse/acsp/controllers/AcspController.java
- src/main/java/uk/gov/companieshouse/acsp/service/AcspService.java
- src/test/java/uk/gov/companieshouse/acsp/controllers/AcspControllerTest.java
- src/test/java/uk/gov/companieshouse/acsp/service/AcspServiceTest.java
Created post endpoint for saving data to MongoDB
IDVA5-840
> Created post endpoint for saving data to MongoDB

- src/main/java/uk/gov/companieshouse/acsp/AcspApplication.java
- src/main/java/uk/gov/companieshouse/acsp/controllers/FilingsController.java
- src/main/java/uk/gov/companieshouse/acsp/models/filing/ACSP.java
- src/main/java/uk/gov/companieshouse/acsp/models/filing/AmlMembership.java
- src/main/java/uk/gov/companieshouse/acsp/models/filing/Item.java
- src/main/java/uk/gov/companieshouse/acsp/service/FilingsService.java
- src/main/java/uk/gov/companieshouse/acsp/service/TransactionService.java
- src/test/java/uk/gov/companieshouse/acsp/service/FilingServiceTest.java
Adding more fields to filing endpoint
> Adding more fields to filing endpoint

- src/main/resources/application.properties
> Fixing phoenix 1

- src/main/java/uk/gov/companieshouse/acsp/service/AcspService.java
- src/main/java/uk/gov/companieshouse/acsp/util/Constants.java
Changing the resume uri pattern
> Changing the resume uri pattern

- src/main/java/uk/gov/companieshouse/acsp/service/AcspService.java
- src/test/java/uk/gov/companieshouse/acsp/service/AcspServiceTest.java
> Updated loggers from info to error

- src/main/java/uk/gov/companieshouse/acsp/controllers/AcspController.java
- src/main/java/uk/gov/companieshouse/acsp/service/AcspService.java
- src/test/java/uk/gov/companieshouse/acsp/controllers/AcspControllerTest.java
- src/test/java/uk/gov/companieshouse/acsp/service/AcspServiceTest.java
Added delete endpoint
IDVA5-851
> Added delete endpoint to remove application from mongodb

- src/main/java/uk/gov/companieshouse/acsp/service/AcspService.java
- src/main/java/uk/gov/companieshouse/acsp/util/TransactionUtils.java
- src/test/java/uk/gov/companieshouse/acsp/service/AcspServiceTest.java
- src/test/java/uk/gov/companieshouse/acsp/util/TransactionUtilsTest.java
change to compare the passed transactionId against transactionId stored in the mongodb
https://companieshouse.atlassian.net/browse/IDVA5-787
* [x ] New feature
* [ x] I have added unit tests for new code that I have added
> IDVA5-787 -compare the transactionId against transactionId stored in the db

- src/main/java/uk/gov/companieshouse/acsp/controllers/AcspController.java
- src/main/java/uk/gov/companieshouse/acsp/exception/InvalidTransactionStatusException.java
- src/main/java/uk/gov/companieshouse/acsp/service/AcspService.java
- src/test/java/uk/gov/companieshouse/acsp/controllers/AcspControllerTest.java
- src/test/java/uk/gov/companieshouse/acsp/service/AcspServiceTest.java
updated put endpoint
https://companieshouse.atlassian.net/browse/IDVA5-861
* [ x] Bug fix
> updated put endpoint

- src/main/java/uk/gov/companieshouse/acsp/models/dao/AcspDataDao.java
- src/main/java/uk/gov/companieshouse/acsp/models/dto/AcspDataDto.java
- src/main/java/uk/gov/companieshouse/acsp/models/filing/ACSP.java
- src/main/java/uk/gov/companieshouse/acsp/models/filing/Address.java
- src/main/java/uk/gov/companieshouse/acsp/models/filing/Appointements.java
- src/main/java/uk/gov/companieshouse/acsp/models/filing/Officers.java
- src/main/java/uk/gov/companieshouse/acsp/models/type/Address.java
- src/main/java/uk/gov/companieshouse/acsp/service/FilingsService.java
- src/test/java/uk/gov/companieshouse/acsp/service/FilingServiceTest.java
Adding business rules in filings endpoint
IDVA5-858
* [x ] New feature
> Adding business rules in filings endpoint

- terraform/groups/ecs-service/locals.tf
> fetching vpc name from stack secrets

- pom.xml
> Upgrading spring boot version to 3.3.1

- src/main/java/uk/gov/companieshouse/acsp/models/enums/BusinessSector.java
- src/main/java/uk/gov/companieshouse/acsp/models/enums/TypeOfBusiness.java
- src/main/java/uk/gov/companieshouse/acsp/service/FilingsService.java
- src/test/java/uk/gov/companieshouse/acsp/service/FilingServiceTest.java
> Idva5- 856 key values 15 char 

- src/main/java/uk/gov/companieshouse/acsp/models/filing/ACSP.java
- src/main/java/uk/gov/companieshouse/acsp/models/filing/Officers.java
- src/main/java/uk/gov/companieshouse/acsp/models/filing/PersonName.java
- src/main/java/uk/gov/companieshouse/acsp/service/FilingsService.java
- src/test/java/uk/gov/companieshouse/acsp/service/FilingServiceTest.java
Creating PersonName in ACSP data model
> Creating PersonName in ACSP data model

- src/main/java/uk/gov/companieshouse/acsp/config/InterceptorConfig.java
- src/main/java/uk/gov/companieshouse/acsp/controllers/FilingsController.java
- terraform/groups/ecs-service/locals.tf
> Making endpoint private

- terraform/groups/ecs-service/profiles/staging-eu-west-2/staging/vars
> remove env file toggle from staging vars

- src/main/java/uk/gov/companieshouse/acsp/controllers/AcspController.java
- src/main/java/uk/gov/companieshouse/acsp/controllers/FilingsController.java
- src/main/java/uk/gov/companieshouse/acsp/models/dao/AMLSupervisoryBodiesDao.java
- src/main/java/uk/gov/companieshouse/acsp/models/dao/AcspDataDao.java
- src/main/java/uk/gov/companieshouse/acsp/models/dao/CompanyDao.java
- src/main/java/uk/gov/companieshouse/acsp/models/dto/AMLSupervisoryBodiesDto.java
- src/main/java/uk/gov/companieshouse/acsp/models/dto/AcspDataDto.java
- src/main/java/uk/gov/companieshouse/acsp/models/dto/CompanyDto.java
- src/main/java/uk/gov/companieshouse/acsp/service/FilingsService.java
- src/main/java/uk/gov/companieshouse/acsp/util/Constants.java
- src/test/java/uk/gov/companieshouse/acsp/interceptor/TransactionInterceptorTest.java
- src/test/java/uk/gov/companieshouse/acsp/service/FilingServiceTest.java
Removing code smells from main branch
> Removing code smells.

- src/main/java/uk/gov/companieshouse/acsp/config/DatabaseConfiguration.java
- src/main/java/uk/gov/companieshouse/acsp/constants/ACSPConstants.java
- src/main/java/uk/gov/companieshouse/acsp/models/dao/AMLSupervisoryBodiesDao.java
- src/main/java/uk/gov/companieshouse/acsp/models/dto/AMLSupervisoryBodiesDto.java
- src/main/java/uk/gov/companieshouse/acsp/notification/EmailNotification.java
- src/main/java/uk/gov/companieshouse/acsp/service/TransactionService.java
- src/test/java/uk/gov/companieshouse/acsp/controllers/CostControllerTest.java
- src/test/java/uk/gov/companieshouse/acsp/service/TransactionServiceTest.java
Removing even more code smells.
> Removing even more code smells.

- src/main/java/uk/gov/companieshouse/acsp/service/FilingsService.java
Removing partnerships from the condition as we need to send business name in case of partnerships
> Removing partnerships from the condition

- src/main/java/uk/gov/companieshouse/acsp/service/FilingsService.java
- src/test/java/uk/gov/companieshouse/acsp/service/FilingServiceTest.java
> Fixing bug 941

- src/main/java/uk/gov/companieshouse/acsp/models/filing/ACSP.java
> IDVA5-978-correcting the company name

- src/main/java/uk/gov/companieshouse/acsp/controllers/AcspController.java
- src/main/java/uk/gov/companieshouse/acsp/service/AcspService.java
- src/test/java/uk/gov/companieshouse/acsp/controllers/AcspControllerTest.java
- src/test/java/uk/gov/companieshouse/acsp/service/AcspServiceTest.java
Updated check has application endpoint to check transaction and filing status
IDVA5-925
> Updated check has application endpoint to check transaction and filing status

- src/main/java/uk/gov/companieshouse/acsp/models/filing/ACSP.java
> reverting changes

- src/main/java/uk/gov/companieshouse/acsp/models/filing/ACSP.java
- src/main/java/uk/gov/companieshouse/acsp/service/FilingsService.java
- src/test/java/uk/gov/companieshouse/acsp/service/FilingServiceTest.java
Fixing the Nationalities joining issue
> Fixing the Nationalities joining issue

- src/main/java/uk/gov/companieshouse/acsp/controllers/AcspController.java
- src/main/java/uk/gov/companieshouse/acsp/service/AcspService.java
- src/test/java/uk/gov/companieshouse/acsp/controllers/AcspControllerTest.java
> Sending company name and number with transaction

- src/test/java/uk/gov/companieshouse/acsp/service/AcspServiceTest.java
> adding tests for company name and number

- src/main/java/uk/gov/companieshouse/acsp/models/filing/ServiceAddress.java
updated filing endpoint field name for isServiceAddressROA
> updated filing endpoint field name for isServiceAddressROA

- src/main/java/uk/gov/companieshouse/acsp/models/filing/ServiceAddress.java
- src/main/java/uk/gov/companieshouse/acsp/service/FilingsService.java
- src/test/java/uk/gov/companieshouse/acsp/service/FilingServiceTest.java
removed acsp wrapper from data
https://companieshouse.atlassian.net/browse/IDVA5-1101
* [x ] Bug fix
> removed acsp wrapper from data

- src/main/java/uk/gov/companieshouse/acsp/service/FilingsService.java
> removed blank line to trigger the pipeline

- src/main/java/uk/gov/companieshouse/acsp/models/dao/CompanyDao.java
- src/main/java/uk/gov/companieshouse/acsp/models/dto/CompanyDto.java
Updating CompanyDao and CompanyDto to only include Company name and Company number
IDVA5-1140
> Updating CompanyDao and CompanyDto 

- src/main/java/uk/gov/companieshouse/acsp/models/dao/AddressDao.java
- src/main/java/uk/gov/companieshouse/acsp/models/dto/AddressDto.java
Updated AddressDao and AddressDto to reflect new address data model
IDAV5-1108
> Updated AddressDao and AddressDto to reflect new data model

- src/main/java/uk/gov/companieshouse/acsp/models/dao/NationalityDao.java
> correcting first_nationality

- routes.yaml
> updated routes,yaml

- routes.yaml
- src/main/java/uk/gov/companieshouse/acsp/util/Constants.java
> Fix environment issue

- terraform/groups/ecs-service/locals.tf
- terraform/groups/ecs-service/main.tf
- terraform/groups/ecs-service/profiles/development-eu-west-2/cidev/vars
- terraform/groups/ecs-service/profiles/development-eu-west-2/phoenix1/vars
- terraform/groups/ecs-service/variables.tf
> terraform updates

- src/test/java/uk/gov/companieshouse/acsp/mapper/EnumTranslatorTest.java
> -update enum test annotation

- src/main/resources/application.properties
Adding snake case strategy for mongo db data
IDVA5-1161
* [x ] Bug fix
> Adding snake case strategy for mongo db data

- src/main/java/uk/gov/companieshouse/acsp/controllers/AcspController.java
- src/main/java/uk/gov/companieshouse/acsp/service/AcspService.java
- src/main/java/uk/gov/companieshouse/acsp/service/TransactionService.java
- src/test/java/uk/gov/companieshouse/acsp/controllers/AcspControllerTest.java
- src/test/java/uk/gov/companieshouse/acsp/service/AcspServiceTest.java
- src/test/java/uk/gov/companieshouse/acsp/service/TransactionServiceTest.java
> Feature/ idva5 1172 new tech debt change delete endpoint

- src/main/java/uk/gov/companieshouse/acsp/models/dao/ApplicantDetailsDao.java
- src/main/java/uk/gov/companieshouse/acsp/models/dto/ApplicantDetailsDto.java
Added correspondence email to applicant details
IDVA5-1133
> Added correspondence email to applicant details

- pom.xml
Fixing CVE updating springframework to 6.1.13
> Fixing CVE updating springframework to 6.1.13

- pom.xml
- src/main/java/uk/gov/companieshouse/acsp/service/FilingsService.java
- src/test/java/uk/gov/companieshouse/acsp/service/FilingServiceTest.java
Updated filing endpoint to map corporate bodies to limited journey and LPs to unincorporated journey
IDVA5-1100
> Updated filing endpoint to map corporate bodies to limited journey and LPs to unincorporated journey

- src/main/java/uk/gov/companieshouse/acsp/service/AcspService.java
> Replace userId with generated application Id

- src/main/java/uk/gov/companieshouse/acsp/service/FilingsService.java
> IDVA5-1257-Json Data Mapping 

- src/main/java/uk/gov/companieshouse/acsp/controllers/AcspController.java
- src/test/java/uk/gov/companieshouse/acsp/controllers/AcspControllerTest.java
- Updating delete endpoint to delete transaction only if transaction status is not closed
IDVA5-1311
> Updating acsp delete endpoint

- src/main/java/uk/gov/companieshouse/acsp/config/InterceptorConfig.java
- src/main/java/uk/gov/companieshouse/acsp/interceptor/LoggingInterceptor.java
- src/test/java/uk/gov/companieshouse/acsp/configuration/InterceptorConfigTest.java
- src/test/java/uk/gov/companieshouse/acsp/interceptor/LoggingInterceptorTest.java
> Add logging interceptor

- src/main/java/uk/gov/companieshouse/acsp/controllers/AcspController.java
- src/main/java/uk/gov/companieshouse/acsp/service/AcspService.java
- src/test/java/uk/gov/companieshouse/acsp/service/AcspServiceTest.java
- Updated the PUT endpoint to return 500 status code if an error occurs.
- Updated PUT endpoint to stop it updating the transaction api if the Company name/number/business name does not change.
IDVA5-1347
> Updated the PUT endpoint

- pom.xml
- src/main/java/uk/gov/companieshouse/acsp/config/InterceptorConfig.java
- src/main/java/uk/gov/companieshouse/acsp/interceptor/AuthenticationInterceptor.java
- src/main/java/uk/gov/companieshouse/acsp/service/AcspService.java
- src/test/java/uk/gov/companieshouse/acsp/configuration/InterceptorConfigTest.java
- src/test/java/uk/gov/companieshouse/acsp/interceptor/AuthenticationInterceptorTest.java
- src/test/java/uk/gov/companieshouse/acsp/service/AcspServiceTest.java
- Added AuthenticationInterceptor to all endpoints, except the heath check, checking if the user has a correct OAuth 2 token.
IDVA5-1310
> Added AuthenticationInterceptor to endpoints

- src/main/java/uk/gov/companieshouse/acsp/service/FilingsService.java
- src/test/java/uk/gov/companieshouse/acsp/service/FilingServiceTest.java
- Updated FilingsService to send the correct email.
IDVA5-1323
> Updated FilingsService to send the correct email.

- src/main/java/uk/gov/companieshouse/acsp/interceptor/AuthenticationInterceptor.java
- src/test/java/uk/gov/companieshouse/acsp/interceptor/AuthenticationInterceptorTest.java
- Updated AuthenticationInterceptor to allow api keys to authenticate requests
IDVA5-1310
> Updated AuthenticationInterceptor

- src/main/java/uk/gov/companieshouse/acsp/service/AcspService.java
Updating last_modified_by_user_id field on acsp_application DB to match user_id against transaction
[https://companieshouse.atlassian.net/browse/IDVA5-1350](url)
> Updating last_modified_by_user_id field to match user_id value

- src/main/java/uk/gov/companieshouse/acsp/models/enums/AMLSupervisoryBodies.java
> IDVA5-1280-Aml supervisory bodies not in smaller case

- src/main/java/uk/gov/companieshouse/acsp/service/FilingsService.java
Updating presenter userId value to match userId of logged in user, rather than application Id
[https://companieshouse.atlassian.net/browse/IDVA5-1350](url)
> Updating presenter userID value to match DB user

- src/main/java/uk/gov/companieshouse/acsp/mapper/ACSPRegDataDtoDaoMapper.java
- src/main/java/uk/gov/companieshouse/acsp/mapper/EnumTranslator.java
- src/main/java/uk/gov/companieshouse/acsp/models/dto/AMLSupervisoryBodiesDto.java
- src/main/java/uk/gov/companieshouse/acsp/models/enums/AMLSupervisoryBodies.java
- src/main/java/uk/gov/companieshouse/acsp/service/FilingsService.java
- src/test/java/uk/gov/companieshouse/acsp/mapper/EnumTranslatorTest.java
- src/test/java/uk/gov/companieshouse/acsp/service/FilingServiceTest.java
> IDVA5-1415-updateEnumForSupervisoryBodies

- pom.xml
> Fixing CVE

- suppress.xml
> Suppressing the CVE

- src/main/java/uk/gov/companieshouse/acsp/service/AcspService.java
> Making application id randomly generated based on the current time.

- src/main/java/uk/gov/companieshouse/acsp/models/dao/Acsp.java
- src/main/java/uk/gov/companieshouse/acsp/repositories/AcspRepository.java
- src/main/java/uk/gov/companieshouse/acsp/service/AcspService.java
- src/test/java/uk/gov/companieshouse/acsp/service/AcspServiceTest.java
Adding data tag being saved in the db
* [ X] New feature
* [ X] I have added unit tests for new code that I have added
* [ X] The code follows our [coding standards](https://github.com/companieshouse/styleguides/blob/master/java.md)
> Adding data tag being saved in the db

- src/main/java/uk/gov/companieshouse/acsp/service/CostService.java
- src/test/java/uk/gov/companieshouse/acsp/service/CostServiceTest.java
- Updating values as per ticket details on cost endpoint
https://companieshouse.atlassian.net/browse/IDVA5-1381 
> Updating values on cost endpoint

- terraform/groups/ecs-service/main.tf
> fixing root file system read permissions

- src/main/java/uk/gov/companieshouse/acsp/service/FilingsService.java
- src/test/java/uk/gov/companieshouse/acsp/service/FilingServiceTest.java
Updated filing description for Limited Journey to include the key word LIMITED
IDVA5-1456
> Updated filing description for Limited Journey

- Makefile
- src/main/java/uk/gov/companieshouse/acsp/service/FilingsService.java
- src/test/java/uk/gov/companieshouse/acsp/service/FilingServiceTest.java
Reverted changes to description for submitting ACSP application
IDVA5-1456
> Reverted changes to description for submitting acsp application

- src/main/java/uk/gov/companieshouse/acsp/service/TransactionService.java
- src/test/java/uk/gov/companieshouse/acsp/service/TransactionServiceTest.java
For deleting the transaction use CHS_API_KEY
IDVA5-1470
* [ x] Bug fix
* [ x] I have added unit tests for new code that I have added
> For deleting the transaction use CHS_API_KEY

- pom.xml
Upgrading parent-pom to latest version
> Upgrading parent-pom to latest version

- pom.xml
- src/main/java/uk/gov/companieshouse/acsp/controllers/AcspController.java
- src/test/java/uk/gov/companieshouse/acsp/controllers/AcspControllerTest.java
- suppress.xml
> Removing the suppressed CVEs

- src/main/java/uk/gov/companieshouse/acsp/service/AcspService.java
null check added for the resource in the transactions as its breaking the latest code with nullpointer error
> null check added for the transaction resource

- terraform/groups/ecs-service/main.tf
> updated ecs modules

- terraform/groups/ecs-service/profiles/staging-eu-west-2/staging/vars
> IDVA5-1396: ACSP Registration - Performance Testing

- terraform/groups/ecs-service/profiles/staging-eu-west-2/staging/vars
> IDVA5-1666: Update CUP for ACSP Registration

- terraform/groups/ecs-service/main.tf
- terraform/groups/ecs-service/profiles/staging-eu-west-2/staging/vars
- terraform/groups/ecs-service/variables.tf
> Updating autoscaling to 70 and healthcheck grace period to 420

- src/main/java/uk/gov/companieshouse/acsp/models/enums/AMLSupervisoryBodies.java
Updating General Council of the Bar to Bar Standards Board (BSB)
IDVA5-1711
> Updating General Council of the Bar to Bar Standards Board (BSB)

- src/main/resources/application.properties
- src/test/resources/application.properties
registration default cost fee updated
> IDVA5-1535 update registration cost default value

- pom.xml
- src/main/java/uk/gov/companieshouse/acsp/controllers/VerifyClientController.java
- src/main/java/uk/gov/companieshouse/acsp/models/email/ClientVerificationEmailData.java
- src/main/java/uk/gov/companieshouse/acsp/service/EmailService.java
- src/main/resources/application.properties
- src/test/java/uk/gov/companieshouse/acsp/controllers/VerifyClientControllerTest.java
- src/test/java/uk/gov/companieshouse/acsp/service/EmailServiceTest.java
Adding endpoint for sending verify a client email confirmation
Added email Service to send emails
IDVA5-1648
> Adding endpoint for sending verify a client email confirmation

- terraform/groups/ecs-service/profiles/live-eu-west-2/live/vars
> Refactoring terraform live tasks configs

- src/main/java/uk/gov/companieshouse/acsp/service/AcspService.java
The change is to remove the Db call to get the Id and use auto generated ID to store the data.
> IDVA5-1770 refactor code

- pom.xml
> Changing version for mapstruct

- pom.xml
Changing the Kafka version to 3.1.0
> Changing the Kafka version to 3.1.0

- src/main/java/uk/gov/companieshouse/acsp/models/filing/Presenter.java
- src/main/java/uk/gov/companieshouse/acsp/models/filing/ServiceAddress.java
- src/main/java/uk/gov/companieshouse/acsp/models/filing/Submission.java
Updating the json values for filing endpoint to be in snake case instead of camel case. This is to ensure consistency across all values
IDVA5-1993
> Updating the json values for filing endpoint to be in snake case instead of camel case

- src/main/java/uk/gov/companieshouse/acsp/mapper/ACSPRegDataDtoDaoMapper.java
- src/main/java/uk/gov/companieshouse/acsp/mapper/EnumTranslator.java
- src/main/java/uk/gov/companieshouse/acsp/models/dao/AcspDataDao.java
- src/main/java/uk/gov/companieshouse/acsp/models/dto/AcspDataDto.java
- src/main/java/uk/gov/companieshouse/acsp/service/AcspService.java
- src/main/java/uk/gov/companieshouse/acsp/util/Constants.java
- src/test/java/uk/gov/companieshouse/acsp/mapper/EnumTranslatorTest.java
- src/test/java/uk/gov/companieshouse/acsp/service/AcspServiceTest.java
Updating ACSP service to accept update ACSP data.
Updating AcspData model to include removed AML bodies to be stored in Mongo
IDVA5-1771
> Updating acsp service to accept update ACSP data.

- pom.xml
- suppress.xml
Updating spring version to fix CVE-2025-24813
> Updating spring version to fix CVE-2025-24813

- pom.xml
Updating spring version and ch parent version
> Updating spring version and ch parent version

- src/main/java/uk/gov/companieshouse/acsp/service/AcspService.java
Removing ACSP number from the transaction. ACSP number needs to be removed from transaction as it is preventing the user from closing transaction as they are not authorised for the company
IDVA5-1772
> Removing acsp number from the transaction

- pom.xml
- src/main/java/uk/gov/companieshouse/acsp/controllers/VerifyClientController.java
> downgrade the kafka version

- src/main/java/uk/gov/companieshouse/acsp/service/FilingsService.java
- src/test/java/uk/gov/companieshouse/acsp/service/FilingServiceTest.java
Updating the JSON filed acsp_details to be aml
IDVA5-1773
> Update to the JSON being sent to chips filing consumer

- src/main/java/uk/gov/companieshouse/acsp/controllers/FilingsController.java
- src/main/java/uk/gov/companieshouse/acsp/models/filing/Filing.java
- src/main/java/uk/gov/companieshouse/acsp/service/FilingsService.java
- src/test/java/uk/gov/companieshouse/acsp/controllers/FilingsControllerTest.java
- src/test/java/uk/gov/companieshouse/acsp/service/FilingServiceTest.java
Updating the filing endpoint to send the submission and presenter fields outside the data field as this is how it is expected in chips-filing-consumer
IDVA5-1774
> Updating the filing endpoint

- src/main/java/uk/gov/companieshouse/acsp/service/FilingsService.java
Adding company number to the filing data.
IDVA5-1774
> Adding company number to the filing data.

- pom.xml
Sonarqube exclude models folder
https://companieshouse.atlassian.net/browse/IDVA5-1893
> IDVA5-1893 - Sonarqube exclude models folder

- src/test/java/uk/gov/companieshouse/acsp/util/ApiLoggerTest.java
SonarQube fix to add assertNull resolve issues 
https://companieshouse.atlassian.net/browse/IDVA5-1893
> IDVA5-1893 - SonarQube fix to add assertNull resolve issues

- README.md
Updating readme for repository
> Updating readme content
